### ISSUE TITLE
CFBundleVersion missing in Info.plist

### ISSUE THREAD

**Issue by cocomode18** [SwiftyBeaver/SwiftyBeaver#355]
Looks like the `CFBundleVersion` is missing in `Info.plist` at v1.8.0, which prevents us from uploading App to iTunes Connect. I believe adding `CURRENT_PROJECT_VERSION` to `SwiftyBeaver.xcodeproj/project.pbxproj` will fix this problem.

- v1.8.0
- using Carthage
- XCode 11.0(11A420a)

![2cce2c1d7613991d7d6979f84e3758ed](https://user-images.githubusercontent.com/1063849/65853011-08de6100-e393-11e9-8eee-b326ff688a45.png)

**Comment by skreutzberger** [comment]
@cocomode18 please try the info.plist from https://github.com/SwiftyBeaver/SwiftyBeaver/pull/356  and report back if it worked for you. Thanks!

**Comment by skreutzberger** [comment]
I released a new version 1.8.1 which should fix the issue. Please verify and report back. Thanks!

**Comment by cocomode18** [comment]
@skreutzberger Thanks for the fast support. I'm sorry, still getting the same error.
Using version 1.7.1 works fine.

**Comment by skreutzberger** [comment]
@lgaches do you have an idea? Did the required content of the info.plist change Xcode 11 :D

**Comment by cocomode18** [comment]
@skreutzberger 
v1.8.2 solved this problem!! Thank you!
