### ISSUE TITLE
Linux Build Broken: NSFileCoordinator Not Implemented on Linux

### ISSUE THREAD

**Issue by xanderdunn** [SwiftyBeaver/SwiftyBeaver#416]
I tried with two versions of Swift. Swift for Tensorflow v0.10, which is based off the 5.3 dev branch:
```
$ which swift
/home/xander/swift-tensorflow-RELEASE-0.10-cuda10.2-cudnn7-ubuntu18.04/usr/bin/swift
$ swift --version
Swift version 5.3-dev (LLVM 55d27a5828, Swift 6a5d84ec08)
Target: x86_64-unknown-linux-gnu
```

and latest official [5.3 dev branch](https://swift.org/download/#snapshots):
```
$ which swift
/home/xander/swift-5.3-DEVELOPMENT-SNAPSHOT-2020-08-31-a-ubuntu18.04/usr/bin/swift
$ swift --version
Swift version 5.3-dev (LLVM 3fa9679add, Swift d24649a4d6)
Target: x86_64-unknown-linux-gnu
```

with result:
```
$ swift build
Cloning https://github.com/SwiftyBeaver/SwiftyBeaver.git
Resolving https://github.com/SwiftyBeaver/SwiftyBeaver.git at 1.9.1
warning: dependency 'Metaprogramming' is not used by any target
/home/xander/dev/plutus_model/.build/checkouts/SwiftyBeaver/Sources/FileDestination.swift:135:27: error: cannot find 'NSFileCo
ordinator' in scope
        let coordinator = NSFileCoordinator(filePresenter: nil)
                          ^~~~~~~~~~~~~~~~~
/home/xander/dev/plutus_model/.build/checkouts/SwiftyBeaver/Sources/FileDestination.swift:135:27: error: cannot find 'NSFileCo
ordinator' in scope
        let coordinator = NSFileCoordinator(filePresenter: nil)
                          ^~~~~~~~~~~~~~~~~
/home/xander/dev/plutus_model/.build/checkouts/SwiftyBeaver/Sources/FileDestination.swift:135:27: error: cannot find 'NSFileC$ordinator' in scope
        let coordinator = NSFileCoordinator(filePresenter: nil)
                          ^~~~~~~~~~~~~~~~~
```

Your continuous integration build is NOT completing successfully ❗See [the latest build](https://app.circleci.com/pipelines/github/SwiftyBeaver/SwiftyBeaver/21/workflows/ddd4dfc9-a25d-42a5-828d-9666d56e12a7/jobs/265):
<img width="1121" alt="Screen Shot 2020-09-13 at 11 55 58" src="https://user-images.githubusercontent.com/1313618/93026064-172f8800-f5b8-11ea-8def-4b439cf2fd5d.png">

The error is that Circle CI returns exit code 0 despite the failure of the `swift build` step.

This was originally discussed in #392 but it was closed without any attempt to resolve it, so I am opening a new issue with additional details. You can see in that issue at least 4 other people have reported this issue as well.

Current workaround in Package.swift:
```
        .package(name: "SwiftyBeaver",
                 url: "https://github.com/SwiftyBeaver/SwiftyBeaver.git",
                 .exact("1.8.4"))

```

**Comment by skreutzberger** [comment]
Thanks! So what should we do?

**Comment by skreutzberger** [comment]
The issue was fixed, thanks for your persistence!

**Comment by sanvean** [comment]
@xanderdunn did v1.9.2 resolve this issue for you? Still seeing the same issues as originally reported in #392 when building for Docker using 5.2-xenial (and also 5.3-xenial). 

So still stuck using v1.8.4 on Linux for the time being...

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner What a troll. WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. SWIFTYBEAVER HAS NOT BEEN BREACHED. SwiftyBeaver is an open-source framework and its used encryption is public, known and trusted since several years. Feel free to contribute source code which makes it safer from your point of view and the contributors and I will consider merging it.
